repos:
  - repo: "https://github.com/ambv/black"
    rev: "23.12.0"
    hooks:
    - id: "black"
      language_version: "python3.9"
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v2.3.0"
    hooks:
    - id: "flake8"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v1.7.1'
    hooks:
    - id: "mypy"
      args: ["--strict", "--ignore-missing-imports"]
